# Generated by Django 5.0.7 on 2024-07-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
